{% set data = load_setup_py_data() %}

package:
  name: emat
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python

requirements:
  build:
    - python {{ python }}
  run:
    - python {{ python }}
    - numpy
    - pandas
    - pydot
    - plotly
    - scipy
    - seaborn
    - pyyaml
    - scikit-learn
    - appdirs
    - matplotlib
    - graphviz
    - plotly-orca  # Plotly Static Image Export
    - ipywidgets
    - joblib
    - dask
    - distributed
    - cloudpickle
    - ipykernel
    - nb_conda
    - jupyter_contrib_nbextensions   # on conda-forge only
    - jupyter
    - notebook
    - pytest
    - pyscaffold
    - ipyparallel
    - pyzmq
    - platypus-opt
    - altair
    - salib
    - sqlalchemy
    - tmip::ema_workbench>=2.1.507,<2.2

test:
  # Python imports
  imports:
    - emat

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
    - pytest

about:
  home: https://tmip-emat.github.io
  license: BSD
  license_file: LICENSE
  summary: exploratory modeling and analysis tools

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
